language: node_js

node_js:
  - 0.10

before_install:
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g karma

install:
  - npm install

before_script:
  - grunt build

script:
  - grunt test